# Generated by Django 4.2.6 on 2023-11-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oneapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies_table',
            name='img',
            field=models.ImageField(default='sweet', upload_to='pictures'),
            preserve_default=False,
        ),
    ]
